CREATE TABLE `rpg_texts` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DE` varchar(1024) DEFAULT '',
  `EN` varchar(1024) DEFAULT '',
  `FR` varchar(1024) DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;
