name: RPG Mob Manager
main: rpgMobManager.RPG_MobManager
version: 0.2.8
description: >
             Manages the mobs on the server.
depend: [RPG Core]
commands:
  mm:
    description: Manages the mobs on the server.
